// Generated by CoffeeScript 1.9.3
(function() {
  var CounterCache;

  CounterCache = (function() {
    function CounterCache() {
      this.cache = {};
    }

    CounterCache.prototype.flushTo = function(queue) {
      var key, name, ref, ref1, results, source, value;
      ref = this.cache;
      results = [];
      for (key in ref) {
        value = ref[key];
        ref1 = key.split(';'), name = ref1[0], source = ref1[1];
        results.push(queue.push(source == null ? {
          name: name,
          value: value
        } : {
          name: name,
          value: value,
          source: source
        }));
      }
      return results;
    };

    CounterCache.prototype.increment = function(name, value) {
      var base;
      if (value == null) {
        value = 1;
      }
      if ((base = this.cache)[name] == null) {
        base[name] = 0;
      }
      return this.cache[name] += value;
    };

    return CounterCache;

  })();

  module.exports = CounterCache;

}).call(this);

//# sourceMappingURL=counter_cache.js.map
